# test runs
#python main_nep.py --project_name BPI19_007 --dataset BPI19 --backbone qwen3-0.6b --lr 0.005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
#python main_nep.py --project_name BPI19_007 --dataset BPI19 --backbone qwen3-1.7b --lr 0.005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
#python main_nep.py --project_name BPI19_007 --dataset BPI19 --backbone qwen3-4b --lr 0.005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info --batch_size 32

#python main_nep.py --project_name BPI19_007 --dataset BPI19 --backbone qwen3-0.6b --lr 0.00005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
#python main_nep.py --project_name BPI19_007 --dataset BPI19 --backbone qwen3-1.7b --lr 0.00005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
#python main_nep.py --project_name BPI19_007 --dataset BPI19 --backbone qwen3-4b --lr 0.00005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info --batch_size 32

#python main_nep.py --project_name BPI19_007 --dataset BPI19 --backbone qwen3-0.6b --lr 0.005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name BPI19_007 --dataset BPI19 --backbone qwen3-1.7b --lr 0.005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name BPI19_007 --dataset BPI19 --backbone qwen3-4b --lr 0.005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info --batch_size 32

python main_nep.py --project_name BPI19_007 --dataset BPI19 --backbone qwen3-0.6b --lr 0.00005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name BPI19_007 --dataset BPI19 --backbone qwen3-1.7b --lr 0.00005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name BPI19_007 --dataset BPI19 --backbone qwen3-4b --lr 0.00005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info --batch_size 32

python main_nep.py --project_name BPI19_007 --dataset BPI19 --backbone qwen3-0.6b --lr 0.005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name BPI19_007 --dataset BPI19 --backbone qwen3-1.7b --lr 0.005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name BPI19_007 --dataset BPI19 --backbone qwen3-4b --lr 0.005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info --batch_size 32

python main_nep.py --project_name BPI19_007 --dataset BPI19 --backbone qwen3-0.6b --lr 0.00005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name BPI19_007 --dataset BPI19 --backbone qwen3-1.7b --lr 0.00005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name BPI19_007 --dataset BPI19 --backbone qwen3-4b --lr 0.00005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info --batch_size 32


python main_nep.py --project_name BPI19_007 --dataset BPI19 --backbone qwen3-0.6b --lr 0.005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name BPI19_007 --dataset BPI19 --backbone qwen3-1.7b --lr 0.005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name BPI19_007 --dataset BPI19 --backbone qwen3-4b --lr 0.005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info --batch_size 32

python main_nep.py --project_name BPI19_007 --dataset BPI19 --backbone qwen3-0.6b --lr 0.00005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name BPI19_007 --dataset BPI19 --backbone qwen3-1.7b --lr 0.00005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name BPI19_007 --dataset BPI19 --backbone qwen3-4b --lr 0.00005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info --batch_size 32
