# --n_layers 1 --hidden_size 64
python main_nep.py --project_name LSTM_001 --dataset BPI12 --backbone rnn --n_layers 1 --hidden_size 64 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time amount --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI17 --backbone rnn --n_layers 1 --hidden_size 64 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time amount --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI15 --backbone rnn --n_layers 1 --hidden_size 64 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI19 --backbone rnn --n_layers 1 --hidden_size 64 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20PrepaidTravelCosts --backbone rnn --n_layers 1 --hidden_size 64 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20RequestForPayment --backbone rnn --n_layers 1 --hidden_size 64 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20TravelPermitData --backbone rnn --n_layers 1 --hidden_size 64 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info

python main_nep.py --project_name LSTM_001 --dataset BPI12 --backbone rnn --n_layers 1 --hidden_size 64 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time amount --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI17 --backbone rnn --n_layers 1 --hidden_size 64 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time amount --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI15 --backbone rnn --n_layers 1 --hidden_size 64 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI19 --backbone rnn --n_layers 1 --hidden_size 64 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20PrepaidTravelCosts --backbone rnn --n_layers 1 --hidden_size 64 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20RequestForPayment --backbone rnn --n_layers 1 --hidden_size 64 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20TravelPermitData --backbone rnn --n_layers 1 --hidden_size 64 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info

python main_nep.py --project_name LSTM_001 --dataset BPI12 --backbone rnn --n_layers 1 --hidden_size 64 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time amount --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI17 --backbone rnn --n_layers 1 --hidden_size 64 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time amount --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI15 --backbone rnn --n_layers 1 --hidden_size 64 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI19 --backbone rnn --n_layers 1 --hidden_size 64 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20PrepaidTravelCosts --backbone rnn --n_layers 1 --hidden_size 64 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20RequestForPayment --backbone rnn --n_layers 1 --hidden_size 64 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20TravelPermitData --backbone rnn --n_layers 1 --hidden_size 64 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info

python main_nep.py --project_name LSTM_001 --dataset BPI12 --backbone rnn --n_layers 1 --hidden_size 64 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time amount --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI17 --backbone rnn --n_layers 1 --hidden_size 64 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time amount --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI15 --backbone rnn --n_layers 1 --hidden_size 64 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI19 --backbone rnn --n_layers 1 --hidden_size 64 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20PrepaidTravelCosts --backbone rnn --n_layers 1 --hidden_size 64 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20RequestForPayment --backbone rnn --n_layers 1 --hidden_size 64 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20TravelPermitData --backbone rnn --n_layers 1 --hidden_size 64 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info

python main_nep.py --project_name LSTM_001 --dataset BPI12 --backbone rnn --n_layers 1 --hidden_size 64 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time amount --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI17 --backbone rnn --n_layers 1 --hidden_size 64 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time amount --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI15 --backbone rnn --n_layers 1 --hidden_size 64 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI19 --backbone rnn --n_layers 1 --hidden_size 64 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20PrepaidTravelCosts --backbone rnn --n_layers 1 --hidden_size 64 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20RequestForPayment --backbone rnn --n_layers 1 --hidden_size 64 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20TravelPermitData --backbone rnn --n_layers 1 --hidden_size 64 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info

# --n_layers 2 --hidden_size 64
python main_nep.py --project_name LSTM_001 --dataset BPI12 --backbone rnn --n_layers 2 --hidden_size 64 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time amount --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI17 --backbone rnn --n_layers 2 --hidden_size 64 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time amount --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI15 --backbone rnn --n_layers 2 --hidden_size 64 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI19 --backbone rnn --n_layers 2 --hidden_size 64 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20PrepaidTravelCosts --backbone rnn --n_layers 2 --hidden_size 64 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20RequestForPayment --backbone rnn --n_layers 2 --hidden_size 64 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20TravelPermitData --backbone rnn --n_layers 2 --hidden_size 64 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info

python main_nep.py --project_name LSTM_001 --dataset BPI12 --backbone rnn --n_layers 2 --hidden_size 64 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time amount --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI17 --backbone rnn --n_layers 2 --hidden_size 64 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time amount --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI15 --backbone rnn --n_layers 2 --hidden_size 64 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI19 --backbone rnn --n_layers 2 --hidden_size 64 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20PrepaidTravelCosts --backbone rnn --n_layers 2 --hidden_size 64 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20RequestForPayment --backbone rnn --n_layers 2 --hidden_size 64 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20TravelPermitData --backbone rnn --n_layers 2 --hidden_size 64 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info

python main_nep.py --project_name LSTM_001 --dataset BPI12 --backbone rnn --n_layers 2 --hidden_size 64 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time amount --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI17 --backbone rnn --n_layers 2 --hidden_size 64 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time amount --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI15 --backbone rnn --n_layers 2 --hidden_size 64 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI19 --backbone rnn --n_layers 2 --hidden_size 64 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20PrepaidTravelCosts --backbone rnn --n_layers 2 --hidden_size 64 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20RequestForPayment --backbone rnn --n_layers 2 --hidden_size 64 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20TravelPermitData --backbone rnn --n_layers 2 --hidden_size 64 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info

python main_nep.py --project_name LSTM_001 --dataset BPI12 --backbone rnn --n_layers 2 --hidden_size 64 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time amount --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI17 --backbone rnn --n_layers 2 --hidden_size 64 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time amount --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI15 --backbone rnn --n_layers 2 --hidden_size 64 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI19 --backbone rnn --n_layers 2 --hidden_size 64 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20PrepaidTravelCosts --backbone rnn --n_layers 2 --hidden_size 64 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20RequestForPayment --backbone rnn --n_layers 2 --hidden_size 64 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20TravelPermitData --backbone rnn --n_layers 2 --hidden_size 64 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info

python main_nep.py --project_name LSTM_001 --dataset BPI12 --backbone rnn --n_layers 2 --hidden_size 64 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time amount --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI17 --backbone rnn --n_layers 2 --hidden_size 64 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time amount --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI15 --backbone rnn --n_layers 2 --hidden_size 64 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI19 --backbone rnn --n_layers 2 --hidden_size 64 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20PrepaidTravelCosts --backbone rnn --n_layers 2 --hidden_size 64 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20RequestForPayment --backbone rnn --n_layers 2 --hidden_size 64 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20TravelPermitData --backbone rnn --n_layers 2 --hidden_size 64 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info

# --n_layers 1 --hidden_size 128
python main_nep.py --project_name LSTM_001 --dataset BPI12 --backbone rnn --n_layers 1 --hidden_size 128 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time amount --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI17 --backbone rnn --n_layers 1 --hidden_size 128 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time amount --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI15 --backbone rnn --n_layers 1 --hidden_size 128 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI19 --backbone rnn --n_layers 1 --hidden_size 128 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20PrepaidTravelCosts --backbone rnn --n_layers 1 --hidden_size 128 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20RequestForPayment --backbone rnn --n_layers 1 --hidden_size 128 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20TravelPermitData --backbone rnn --n_layers 1 --hidden_size 128 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info

python main_nep.py --project_name LSTM_001 --dataset BPI12 --backbone rnn --n_layers 1 --hidden_size 128 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time amount --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI17 --backbone rnn --n_layers 1 --hidden_size 128 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time amount --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI15 --backbone rnn --n_layers 1 --hidden_size 128 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI19 --backbone rnn --n_layers 1 --hidden_size 128 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20PrepaidTravelCosts --backbone rnn --n_layers 1 --hidden_size 128 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20RequestForPayment --backbone rnn --n_layers 1 --hidden_size 128 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20TravelPermitData --backbone rnn --n_layers 1 --hidden_size 128 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info

python main_nep.py --project_name LSTM_001 --dataset BPI12 --backbone rnn --n_layers 1 --hidden_size 128 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time amount --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI17 --backbone rnn --n_layers 1 --hidden_size 128 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time amount --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI15 --backbone rnn --n_layers 1 --hidden_size 128 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI19 --backbone rnn --n_layers 1 --hidden_size 128 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20PrepaidTravelCosts --backbone rnn --n_layers 1 --hidden_size 128 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20RequestForPayment --backbone rnn --n_layers 1 --hidden_size 128 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20TravelPermitData --backbone rnn --n_layers 1 --hidden_size 128 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info

python main_nep.py --project_name LSTM_001 --dataset BPI12 --backbone rnn --n_layers 1 --hidden_size 128 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time amount --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI17 --backbone rnn --n_layers 1 --hidden_size 128 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time amount --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI15 --backbone rnn --n_layers 1 --hidden_size 128 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI19 --backbone rnn --n_layers 1 --hidden_size 128 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20PrepaidTravelCosts --backbone rnn --n_layers 1 --hidden_size 128 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20RequestForPayment --backbone rnn --n_layers 1 --hidden_size 128 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20TravelPermitData --backbone rnn --n_layers 1 --hidden_size 128 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info

python main_nep.py --project_name LSTM_001 --dataset BPI12 --backbone rnn --n_layers 1 --hidden_size 128 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time amount --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI17 --backbone rnn --n_layers 1 --hidden_size 128 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time amount --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI15 --backbone rnn --n_layers 1 --hidden_size 128 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI19 --backbone rnn --n_layers 1 --hidden_size 128 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20PrepaidTravelCosts --backbone rnn --n_layers 1 --hidden_size 128 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20RequestForPayment --backbone rnn --n_layers 1 --hidden_size 128 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20TravelPermitData --backbone rnn --n_layers 1 --hidden_size 128 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info


# --n_layers 2 --hidden_size 128
python main_nep.py --project_name LSTM_001 --dataset BPI12 --backbone rnn --n_layers 2 --hidden_size 128 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time amount --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI17 --backbone rnn --n_layers 2 --hidden_size 128 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time amount --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI15 --backbone rnn --n_layers 2 --hidden_size 128 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI19 --backbone rnn --n_layers 2 --hidden_size 128 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20PrepaidTravelCosts --backbone rnn --n_layers 2 --hidden_size 128 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20RequestForPayment --backbone rnn --n_layers 2 --hidden_size 128 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20TravelPermitData --backbone rnn --n_layers 2 --hidden_size 128 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info

python main_nep.py --project_name LSTM_001 --dataset BPI12 --backbone rnn --n_layers 2 --hidden_size 128 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time amount --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI17 --backbone rnn --n_layers 2 --hidden_size 128 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time amount --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI15 --backbone rnn --n_layers 2 --hidden_size 128 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI19 --backbone rnn --n_layers 2 --hidden_size 128 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20PrepaidTravelCosts --backbone rnn --n_layers 2 --hidden_size 128 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20RequestForPayment --backbone rnn --n_layers 2 --hidden_size 128 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20TravelPermitData --backbone rnn --n_layers 2 --hidden_size 128 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info

python main_nep.py --project_name LSTM_001 --dataset BPI12 --backbone rnn --n_layers 2 --hidden_size 128 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time amount --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI17 --backbone rnn --n_layers 2 --hidden_size 128 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time amount --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI15 --backbone rnn --n_layers 2 --hidden_size 128 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI19 --backbone rnn --n_layers 2 --hidden_size 128 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20PrepaidTravelCosts --backbone rnn --n_layers 2 --hidden_size 128 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20RequestForPayment --backbone rnn --n_layers 2 --hidden_size 128 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20TravelPermitData --backbone rnn --n_layers 2 --hidden_size 128 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info

python main_nep.py --project_name LSTM_001 --dataset BPI12 --backbone rnn --n_layers 2 --hidden_size 128 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time amount --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI17 --backbone rnn --n_layers 2 --hidden_size 128 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time amount --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI15 --backbone rnn --n_layers 2 --hidden_size 128 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI19 --backbone rnn --n_layers 2 --hidden_size 128 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20PrepaidTravelCosts --backbone rnn --n_layers 2 --hidden_size 128 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20RequestForPayment --backbone rnn --n_layers 2 --hidden_size 128 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20TravelPermitData --backbone rnn --n_layers 2 --hidden_size 128 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info

python main_nep.py --project_name LSTM_001 --dataset BPI12 --backbone rnn --n_layers 2 --hidden_size 128 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time amount --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI17 --backbone rnn --n_layers 2 --hidden_size 128 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time amount --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI15 --backbone rnn --n_layers 2 --hidden_size 128 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI19 --backbone rnn --n_layers 2 --hidden_size 128 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20PrepaidTravelCosts --backbone rnn --n_layers 2 --hidden_size 128 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20RequestForPayment --backbone rnn --n_layers 2 --hidden_size 128 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20TravelPermitData --backbone rnn --n_layers 2 --hidden_size 128 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info


# --n_layers 1 --hidden_size 256
python main_nep.py --project_name LSTM_001 --dataset BPI12 --backbone rnn --n_layers 1 --hidden_size 256 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time amount --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI17 --backbone rnn --n_layers 1 --hidden_size 256 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time amount --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI15 --backbone rnn --n_layers 1 --hidden_size 256 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI19 --backbone rnn --n_layers 1 --hidden_size 256 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20PrepaidTravelCosts --backbone rnn --n_layers 1 --hidden_size 256 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20RequestForPayment --backbone rnn --n_layers 1 --hidden_size 256 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20TravelPermitData --backbone rnn --n_layers 1 --hidden_size 256 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info

python main_nep.py --project_name LSTM_001 --dataset BPI12 --backbone rnn --n_layers 1 --hidden_size 256 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time amount --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI17 --backbone rnn --n_layers 1 --hidden_size 256 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time amount --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI15 --backbone rnn --n_layers 1 --hidden_size 256 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI19 --backbone rnn --n_layers 1 --hidden_size 256 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20PrepaidTravelCosts --backbone rnn --n_layers 1 --hidden_size 256 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20RequestForPayment --backbone rnn --n_layers 1 --hidden_size 256 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20TravelPermitData --backbone rnn --n_layers 1 --hidden_size 256 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info

python main_nep.py --project_name LSTM_001 --dataset BPI12 --backbone rnn --n_layers 1 --hidden_size 256 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time amount --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI17 --backbone rnn --n_layers 1 --hidden_size 256 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time amount --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI15 --backbone rnn --n_layers 1 --hidden_size 256 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI19 --backbone rnn --n_layers 1 --hidden_size 256 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20PrepaidTravelCosts --backbone rnn --n_layers 1 --hidden_size 256 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20RequestForPayment --backbone rnn --n_layers 1 --hidden_size 256 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20TravelPermitData --backbone rnn --n_layers 1 --hidden_size 256 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info

python main_nep.py --project_name LSTM_001 --dataset BPI12 --backbone rnn --n_layers 1 --hidden_size 256 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time amount --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI17 --backbone rnn --n_layers 1 --hidden_size 256 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time amount --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI15 --backbone rnn --n_layers 1 --hidden_size 256 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI19 --backbone rnn --n_layers 1 --hidden_size 256 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20PrepaidTravelCosts --backbone rnn --n_layers 1 --hidden_size 256 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20RequestForPayment --backbone rnn --n_layers 1 --hidden_size 256 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20TravelPermitData --backbone rnn --n_layers 1 --hidden_size 256 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info

python main_nep.py --project_name LSTM_001 --dataset BPI12 --backbone rnn --n_layers 1 --hidden_size 256 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time amount --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI17 --backbone rnn --n_layers 1 --hidden_size 256 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time amount --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI15 --backbone rnn --n_layers 1 --hidden_size 256 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI19 --backbone rnn --n_layers 1 --hidden_size 256 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20PrepaidTravelCosts --backbone rnn --n_layers 1 --hidden_size 256 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20RequestForPayment --backbone rnn --n_layers 1 --hidden_size 256 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20TravelPermitData --backbone rnn --n_layers 1 --hidden_size 256 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info


# --n_layers 2 --hidden_size 256
python main_nep.py --project_name LSTM_001 --dataset BPI12 --backbone rnn --n_layers 2 --hidden_size 256 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time amount --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI17 --backbone rnn --n_layers 2 --hidden_size 256 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time amount --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI15 --backbone rnn --n_layers 2 --hidden_size 256 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI19 --backbone rnn --n_layers 2 --hidden_size 256 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20PrepaidTravelCosts --backbone rnn --n_layers 2 --hidden_size 256 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20RequestForPayment --backbone rnn --n_layers 2 --hidden_size 256 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20TravelPermitData --backbone rnn --n_layers 2 --hidden_size 256 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info

python main_nep.py --project_name LSTM_001 --dataset BPI12 --backbone rnn --n_layers 2 --hidden_size 256 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time amount --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI17 --backbone rnn --n_layers 2 --hidden_size 256 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time amount --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI15 --backbone rnn --n_layers 2 --hidden_size 256 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI19 --backbone rnn --n_layers 2 --hidden_size 256 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20PrepaidTravelCosts --backbone rnn --n_layers 2 --hidden_size 256 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20RequestForPayment --backbone rnn --n_layers 2 --hidden_size 256 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20TravelPermitData --backbone rnn --n_layers 2 --hidden_size 256 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info

python main_nep.py --project_name LSTM_001 --dataset BPI12 --backbone rnn --n_layers 2 --hidden_size 256 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time amount --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI17 --backbone rnn --n_layers 2 --hidden_size 256 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time amount --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI15 --backbone rnn --n_layers 2 --hidden_size 256 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI19 --backbone rnn --n_layers 2 --hidden_size 256 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20PrepaidTravelCosts --backbone rnn --n_layers 2 --hidden_size 256 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20RequestForPayment --backbone rnn --n_layers 2 --hidden_size 256 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20TravelPermitData --backbone rnn --n_layers 2 --hidden_size 256 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info

python main_nep.py --project_name LSTM_001 --dataset BPI12 --backbone rnn --n_layers 2 --hidden_size 256 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time amount --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI17 --backbone rnn --n_layers 2 --hidden_size 256 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time amount --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI15 --backbone rnn --n_layers 2 --hidden_size 256 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI19 --backbone rnn --n_layers 2 --hidden_size 256 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20PrepaidTravelCosts --backbone rnn --n_layers 2 --hidden_size 256 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20RequestForPayment --backbone rnn --n_layers 2 --hidden_size 256 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20TravelPermitData --backbone rnn --n_layers 2 --hidden_size 256 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info

python main_nep.py --project_name LSTM_001 --dataset BPI12 --backbone rnn --n_layers 2 --hidden_size 256 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time amount --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI17 --backbone rnn --n_layers 2 --hidden_size 256 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time amount --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI15 --backbone rnn --n_layers 2 --hidden_size 256 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI19 --backbone rnn --n_layers 2 --hidden_size 256 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20PrepaidTravelCosts --backbone rnn --n_layers 2 --hidden_size 256 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20RequestForPayment --backbone rnn --n_layers 2 --hidden_size 256 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name LSTM_001 --dataset BPI20TravelPermitData --backbone rnn --n_layers 2 --hidden_size 256 --lr 5e-4  --val_size .1 --val_split prefix --patience 10 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
