# 5 nanogpt
python main_nep.py --project_name BPI12_002 --dataset BPI12 --backbone nanogpt --fine_tuning none --n_layers 4 --n_heads 8 --hidden_size 512 --lr 0.005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time amount --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name BPI12_002 --dataset BPI12 --backbone nanogpt --fine_tuning none --n_layers 4 --n_heads 8 --hidden_size 512 --lr 0.005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time amount --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name BPI12_002 --dataset BPI12 --backbone nanogpt --fine_tuning none --n_layers 4 --n_heads 8 --hidden_size 512 --lr 0.005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time amount --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name BPI12_002 --dataset BPI12 --backbone nanogpt --fine_tuning none --n_layers 4 --n_heads 8 --hidden_size 512 --lr 0.005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time amount --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name BPI12_002 --dataset BPI12 --backbone nanogpt --fine_tuning none --n_layers 4 --n_heads 8 --hidden_size 512 --lr 0.005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time amount --lifecycle --wandb --compile --append_run_info

python main_nep.py --project_name BPI12_002 --dataset BPI12 --backbone nanogpt --fine_tuning none --n_layers 12 --n_heads 12 --hidden_size 768 --lr 0.005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time amount --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name BPI12_002 --dataset BPI12 --backbone nanogpt --fine_tuning none --n_layers 12 --n_heads 12 --hidden_size 768 --lr 0.005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time amount --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name BPI12_002 --dataset BPI12 --backbone nanogpt --fine_tuning none --n_layers 12 --n_heads 12 --hidden_size 768 --lr 0.005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time amount --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name BPI12_002 --dataset BPI12 --backbone nanogpt --fine_tuning none --n_layers 12 --n_heads 12 --hidden_size 768 --lr 0.005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time amount --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name BPI12_002 --dataset BPI12 --backbone nanogpt --fine_tuning none --n_layers 12 --n_heads 12 --hidden_size 768 --lr 0.005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time amount --lifecycle --wandb --compile --append_run_info

