# 5 gpt2-mini
python main_nep.py --project_name BPI15_005 --dataset BPI15 --backbone gpt2-mini --lr 0.0005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name BPI15_005 --dataset BPI15 --backbone gpt2-mini --lr 0.0005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name BPI15_005 --dataset BPI15 --backbone gpt2-mini --lr 0.0005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name BPI15_005 --dataset BPI15 --backbone gpt2-mini --lr 0.0005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name BPI15_005 --dataset BPI15 --backbone gpt2-mini --lr 0.0005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info

python main_nep.py --project_name BPI15_005 --dataset BPI15 --backbone gpt2-small --lr 0.0005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name BPI15_005 --dataset BPI15 --backbone gpt2-small --lr 0.0005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name BPI15_005 --dataset BPI15 --backbone gpt2-small --lr 0.0005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name BPI15_005 --dataset BPI15 --backbone gpt2-small --lr 0.0005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name BPI15_005 --dataset BPI15 --backbone gpt2-small --lr 0.0005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info

python main_nep.py --project_name BPI15_005 --dataset BPI15 --backbone gpt2-medium --lr 0.00005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name BPI15_005 --dataset BPI15 --backbone gpt2-medium --lr 0.00005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name BPI15_005 --dataset BPI15 --backbone gpt2-medium --lr 0.00005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name BPI15_005 --dataset BPI15 --backbone gpt2-medium --lr 0.00005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name BPI15_005 --dataset BPI15 --backbone gpt2-medium --lr 0.00005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info

python main_nep.py --project_name BPI15_005 --dataset BPI15 --backbone gpt2-large --lr 0.00005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name BPI15_005 --dataset BPI15 --backbone gpt2-large --lr 0.00005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name BPI15_005 --dataset BPI15 --backbone gpt2-large --lr 0.00005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name BPI15_005 --dataset BPI15 --backbone gpt2-large --lr 0.00005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name BPI15_005 --dataset BPI15 --backbone gpt2-large --lr 0.00005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info

#python main_nep.py --project_name BPI15_005 --dataset BPI15 --backbone gpt2-xl --lr 0.0005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
#python main_nep.py --project_name BPI15_005 --dataset BPI15 --backbone gpt2-xl --lr 0.0005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
#python main_nep.py --project_name BPI15_005 --dataset BPI15 --backbone gpt2-xl --lr 0.0005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
#python main_nep.py --project_name BPI15_005 --dataset BPI15 --backbone gpt2-xl --lr 0.0005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
#python main_nep.py --project_name BPI15_005 --dataset BPI15 --backbone gpt2-xl --lr 0.0005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
