# BPI20PrepaidTravelCosts 
python main_nep.py --project_name BPI20_003 --dataset BPI20PrepaidTravelCosts  --backbone qwen3-0.6b --lr 0.0005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name BPI20_003 --dataset BPI20PrepaidTravelCosts  --backbone qwen3-1.7b --lr 0.0005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name BPI20_003 --dataset BPI20PrepaidTravelCosts  --backbone qwen3-4b --lr 0.0005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info

python main_nep.py --project_name BPI20_003 --dataset BPI20PrepaidTravelCosts  --backbone qwen3-0.6b --lr 0.0005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name BPI20_003 --dataset BPI20PrepaidTravelCosts  --backbone qwen3-1.7b --lr 0.0005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name BPI20_003 --dataset BPI20PrepaidTravelCosts  --backbone qwen3-4b --lr 0.0005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info

python main_nep.py --project_name BPI20_003 --dataset BPI20PrepaidTravelCosts  --backbone qwen3-0.6b --lr 0.0005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name BPI20_003 --dataset BPI20PrepaidTravelCosts  --backbone qwen3-1.7b --lr 0.0005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name BPI20_003 --dataset BPI20PrepaidTravelCosts  --backbone qwen3-4b --lr 0.0005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info

python main_nep.py --project_name BPI20_003 --dataset BPI20PrepaidTravelCosts  --backbone qwen3-0.6b --lr 0.0005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name BPI20_003 --dataset BPI20PrepaidTravelCosts  --backbone qwen3-1.7b --lr 0.0005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name BPI20_003 --dataset BPI20PrepaidTravelCosts  --backbone qwen3-4b --lr 0.0005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info

python main_nep.py --project_name BPI20_003 --dataset BPI20PrepaidTravelCosts  --backbone qwen3-0.6b --lr 0.0005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name BPI20_003 --dataset BPI20PrepaidTravelCosts  --backbone qwen3-1.7b --lr 0.0005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name BPI20_003 --dataset BPI20PrepaidTravelCosts  --backbone qwen3-4b --lr 0.0005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info


#BPI20TravelPermitData 
python main_nep.py --project_name BPI20_003 --dataset BPI20TravelPermitData  --backbone qwen3-0.6b --lr 0.0005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name BPI20_003 --dataset BPI20TravelPermitData  --backbone qwen3-1.7b --lr 0.0005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name BPI20_003 --dataset BPI20TravelPermitData  --backbone qwen3-4b --lr 0.0005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info

python main_nep.py --project_name BPI20_003 --dataset BPI20TravelPermitData  --backbone qwen3-0.6b --lr 0.0005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name BPI20_003 --dataset BPI20TravelPermitData  --backbone qwen3-1.7b --lr 0.0005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name BPI20_003 --dataset BPI20TravelPermitData  --backbone qwen3-4b --lr 0.0005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info

python main_nep.py --project_name BPI20_003 --dataset BPI20TravelPermitData  --backbone qwen3-0.6b --lr 0.0005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name BPI20_003 --dataset BPI20TravelPermitData  --backbone qwen3-1.7b --lr 0.0005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name BPI20_003 --dataset BPI20TravelPermitData  --backbone qwen3-4b --lr 0.0005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info

python main_nep.py --project_name BPI20_003 --dataset BPI20TravelPermitData  --backbone qwen3-0.6b --lr 0.0005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name BPI20_003 --dataset BPI20TravelPermitData  --backbone qwen3-1.7b --lr 0.0005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name BPI20_003 --dataset BPI20TravelPermitData  --backbone qwen3-4b --lr 0.0005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info

python main_nep.py --project_name BPI20_003 --dataset BPI20TravelPermitData  --backbone qwen3-0.6b --lr 0.0005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name BPI20_003 --dataset BPI20TravelPermitData  --backbone qwen3-1.7b --lr 0.0005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name BPI20_003 --dataset BPI20TravelPermitData  --backbone qwen3-4b --lr 0.0005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info


#BPI20RequestForPayment
python main_nep.py --project_name BPI20_003 --dataset BPI20RequestForPayment --backbone qwen3-0.6b --lr 0.0005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name BPI20_003 --dataset BPI20RequestForPayment --backbone qwen3-1.7b --lr 0.0005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name BPI20_003 --dataset BPI20RequestForPayment --backbone qwen3-4b --lr 0.0005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info

python main_nep.py --project_name BPI20_003 --dataset BPI20RequestForPayment --backbone qwen3-0.6b --lr 0.0005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name BPI20_003 --dataset BPI20RequestForPayment --backbone qwen3-1.7b --lr 0.0005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name BPI20_003 --dataset BPI20RequestForPayment --backbone qwen3-4b --lr 0.0005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info

python main_nep.py --project_name BPI20_003 --dataset BPI20RequestForPayment --backbone qwen3-0.6b --lr 0.0005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name BPI20_003 --dataset BPI20RequestForPayment --backbone qwen3-1.7b --lr 0.0005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name BPI20_003 --dataset BPI20RequestForPayment --backbone qwen3-4b --lr 0.0005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info

python main_nep.py --project_name BPI20_003 --dataset BPI20RequestForPayment --backbone qwen3-0.6b --lr 0.0005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name BPI20_003 --dataset BPI20RequestForPayment --backbone qwen3-1.7b --lr 0.0005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name BPI20_003 --dataset BPI20RequestForPayment --backbone qwen3-4b --lr 0.0005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info

python main_nep.py --project_name BPI20_003 --dataset BPI20RequestForPayment --backbone qwen3-0.6b --lr 0.0005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name BPI20_003 --dataset BPI20RequestForPayment --backbone qwen3-1.7b --lr 0.0005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
python main_nep.py --project_name BPI20_003 --dataset BPI20RequestForPayment --backbone qwen3-4b --lr 0.0005  --val_size .1 --val_split prefix --patience 10 --freeze_layers 1 -1 --categorical_features activity resource --continuous_features accumulated_time  --lifecycle --wandb --compile --append_run_info
